server {
    listen 5173;server_name 104.199.74.113;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    location /core_api/ {
        proxy_pass http://34.38.168.89;
    }
    location /mantle_api/ {
        proxy_pass http://34.38.148.177;
    }
}