default:
  image: $CI_REGISTRY/$CI_$CI_PROJECT_NAMESPACE/ttr-gitlab-image:34dfa6a5
  services:
    - docker:24.0.7-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  GCR_REGISTRY_IMAGE: gcr.io/ip2-ticket-to-ride-project/frontend
  TAR_FILE_NAME: ttr-frontend-image.tar

stages:
  - quality
  - build-image
  - publish-image
  - deploy

linting:
  stage: quality
  script:
    - echo "Linting the application..."
    - cd ./frontend
    - npm run lint
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

build-image:
  stage: build-image
  script:
    - echo "Building the application..."
    - docker build . -t $GCR_REGISTRY_IMAGE:latest
    - docker save -o $TAR_FILE_NAME $GCR_REGISTRY_IMAGE:latest
  artifacts:
    expire_in: 1 hours
    paths:
      - $TAR_FILE_NAME

publish-image:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: publish-image
  dependencies:
    - build-image
  script:
    - echo "Publishing the application..."
    - docker load -q -i $TAR_FILE_NAME
    - echo $GCP_SA_KEY | base64 -d | docker login -u _json_key --password-stdin https://gcr.io
    - docker push $GCR_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  dependencies:
    - publish-image
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Deploying the application..."
    - echo $GCP_SA_KEY > encrypted-key-file
    - base64 -d encrypted-key-file > key-file.json
    - gcloud auth activate-service-account --key-file=key-file.json
    - gcloud components install gke-gcloud-auth-plugin --quiet
    - gcloud config set project ip2-ticket-to-ride-project
    - gcloud container clusters get-credentials cluster-team13 --zone europe-west1-d
    - kubectl rollout restart deployment frontend-deployment